// <auto-generated />
using System;
using GeneralDLL.Core.RedisCash;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeneralDLL.Migrations
{
    [DbContext(typeof(CacheDBContext))]
    partial class CacheDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeneralDLL.Core.RedisCash.Domains.CashBackup", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateExpire")
                        .HasColumnType("datetime2");

                    b.Property<string>("key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("value1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("value2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("value3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("CashBackup");
                });
#pragma warning restore 612, 618
        }
    }
}
