// <auto-generated />
using System;
using GeneralDLL.Core.ErrorController;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeneralDLL.Core.Migrations
{
    [DbContext(typeof(ErrorReportDBContext))]
    partial class ErrorReportDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeneralDLL.Core.ErrorController.Domain.ErrorReport", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("Message1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Program")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("layer1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("layer10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("layer11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("layer12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("layer13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("layer14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("layer15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("layer16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("layer17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("layer18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("layer19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("layer2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("layer20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("layer3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("layer4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("layer5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("layer6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("layer7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("layer8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("layer9")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("ErrorReports");
                });
#pragma warning restore 612, 618
        }
    }
}
